Add configure link tests for nanosleep() from Core.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6706,6 +6706,101 @@ rm -rf conftest.dSYM
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 
+
+{ $as_echo "$as_me:$LINENO: checking for library containing nanosleep" >&5
+$as_echo_n "checking for library containing nanosleep... " >&6; }
+if test "${ac_cv_search_nanosleep+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char nanosleep ();
+int
+main ()
+{
+return nanosleep ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' rt posix4; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then
+  ac_cv_search_nanosleep=$ac_res
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -rf conftest.dSYM
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_nanosleep+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_nanosleep+set}" = set; then
+  :
+else
+  ac_cv_search_nanosleep=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ $as_echo "$as_me:$LINENO: result: $ac_cv_search_nanosleep" >&5
+$as_echo "$ac_cv_search_nanosleep" >&6; }
+ac_res=$ac_cv_search_nanosleep
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+else
+
+    echo "Error: nanosleep() needed for timing operations."
+    exit 1
+
+fi
+
+
+
 init_dir=/etc/rc.d/init.d
 if test -d /etc/rc.d/init.d; then
     init_dir="/etc/rc.d/init.d"
@@ -7167,18 +7262,16 @@ fi
 USE_NANOSLEEP=yes
 # Check whether --enable-nanosleep was given.
 if test "${enable_nanosleep+set}" = set; then
-  enableval=$enable_nanosleep;
-fi
-
-if test x$enable_nanosleep = xno; then
-  USE_NANOSLEEP=no
+  enableval=$enable_nanosleep; USE_NANOSLEEP=$enableval
 else
   USE_NANOSLEEP=yes
+
 fi
 
 if test x$USE_NANOSLEEP = xyes ; then
-	cat >>confdefs.h <<_ACEOF
-#define USE_NANOSLEEP 1
+
+cat >>confdefs.h <<_ACEOF
+#define USE_NANOSLEEP /**/
 _ACEOF
 
 fi
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -131,6 +131,14 @@ AC_TRY_LINK([
     [struct sockaddr_un su; int i = SUN_LEN(&su);],
     [AC_DEFINE(HAVE_SUN_LEN)], )
 
+
+dnl Solaris needs rt or posix4 libraries for nanosleep()
+AC_SEARCH_LIBS(nanosleep,[rt posix4],,[
+    echo "Error: nanosleep() needed for timing operations."
+    exit 1
+    ])
+
+
 dnl Check for location of init scripts
 init_dir=/etc/rc.d/init.d
 if test -d /etc/rc.d/init.d; then
@@ -393,10 +401,14 @@ if test x$check_for_ssl = xyes; then
 fi
 
 USE_NANOSLEEP=yes
-AC_ARG_ENABLE(nanosleep,AC_HELP_STRING([--enable-nanosleep],[enables use of nanosleep (instead of sleep) in event timing]))
-AS_IF([test x$enable_nanosleep = xno],[USE_NANOSLEEP=no],[USE_NANOSLEEP=yes])
+AC_ARG_ENABLE(nanosleep,
+	AC_HELP_STRING([--enable-nanosleep],
+		[enables use of nanosleep (instead of sleep) in event timing]),
+	USE_NANOSLEEP=$enableval,
+	USE_NANOSLEEP=yes
+)
 if test x$USE_NANOSLEEP = xyes ; then
-	AC_DEFINE_UNQUOTED(USE_NANOSLEEP)
+	AC_DEFINE_UNQUOTED(USE_NANOSLEEP,,[enables use of nanosleep (instead of sleep)])
 fi
 
 AC_OUTPUT(Makefile src/Makefile docs/docbook/en-en/Makefile subst)
