Added SSL Support to NDOUtils
Thanks to Jean Gabes for the patch - http://tracker.nagios.org/view.php?id=38

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA INSTALL build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE CPP EGREP OTHERLIBS SOCKETLIBS LIBWRAPLIBS init_dir MOD_CFLAGS MOD_LDFLAGS np_mysql_config DBCFLAGS DBLDFLAGS DBLIBS ndo2db_user ndo2db_group INSTALL_OPTS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA INSTALL build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE CPP EGREP OTHERLIBS SOCKETLIBS LIBWRAPLIBS init_dir MOD_CFLAGS MOD_LDFLAGS np_mysql_config DBCFLAGS DBLDFLAGS DBLIBS ndo2db_user ndo2db_group INSTALL_OPTS HAVE_SSL LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -846,6 +846,7 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
 --enable-mysql enables MySQL database support
+--enable-ssl enables native SSL support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -856,6 +857,10 @@ Optional Packages:
                           mysql_config in PATH
 --with-ndo2db-user=<user> sets user name to run NDO2DB
 --with-ndo2db-group=<group> sets group name to run NDO2DB
+--with-ssl=DIR sets location of the SSL installation
+--with-ssl-inc=DIR sets location of the SSL include files
+--with-ssl-lib=DIR sets location of the SSL libraries
+--with-kerberos-inc=DIR sets location of the Kerberos include files
 
 Some influential environment variables:
   CC          C compiler command
@@ -6194,6 +6199,162 @@ INSTALL_OPTS="-o $ndo2db_user -g $ndo2db_group"
 
 
 
+# Check whether --enable-ssl or --disable-ssl was given.
+if test "${enable_ssl+set}" = set; then
+  enableval="$enable_ssl"
+
+	if test x$enableval = xyes; then
+		check_for_ssl=yes
+	else
+		check_for_ssl=no
+	fi
+
+else
+  check_for_ssl=yes
+fi;
+
+ssl_dir=
+ssl_inc_dir=
+ssl_lib_dir=
+
+# Check whether --with-ssl or --without-ssl was given.
+if test "${with_ssl+set}" = set; then
+  withval="$with_ssl"
+
+	ssl_dir=$withval
+
+fi;
+
+# Check whether --with-ssl-inc or --without-ssl-inc was given.
+if test "${with_ssl_inc+set}" = set; then
+  withval="$with_ssl_inc"
+
+	ssl_inc_dir=$withval
+
+fi;
+
+# Check whether --with-ssl-lib or --without-ssl-lib was given.
+if test "${with_ssl_lib+set}" = set; then
+  withval="$with_ssl_lib"
+
+	ssl_lib_dir=$withval
+
+fi;
+
+# Check whether --with-kerberos-inc or --without-kerberos-inc was given.
+if test "${with_kerberos_inc+set}" = set; then
+  withval="$with_kerberos_inc"
+
+	kerberos_inc_dir=$withval
+
+fi;
+
+if test x$check_for_ssl = xyes; then
+	echo "$as_me:$LINENO: checking for SSL headers" >&5
+echo $ECHO_N "checking for SSL headers... $ECHO_C" >&6
+	found_ssl=no
+	for dir in $ssl_inc_dir $ssl_dir /usr/local/openssl /usr/local/ssl /usr/lib/ssl /usr/ssl /usr/pkg /usr/local /usr /usr/freeware/lib/openssl; do
+		ssldir="$dir"
+		if test -f "$dir/include/openssl/ssl.h"; then
+			found_ssl=yes
+			CFLAGS="$CFLAGS -I$dir/include/openssl -I$ssldir/include"
+			sslincdir="$dir/include/openssl"
+		        break
+		fi
+		if test -f "$dir/include/ssl.h"; then
+			found_ssl=yes
+			CFLAGS="$CFLAGS -I$dir/include"
+			sslincdir="$dir/include"
+		        break
+		fi
+		if test -f "$dir/ssl.h"; then
+			found_ssl=yes
+			CFLAGS="$CFLAGS -I$dir"
+			sslincdir="$dir"
+			ssldir="$dir/.."
+		        break
+		fi
+		if test -f "$dir/openssl/ssl.h"; then
+			found_ssl=yes
+			CFLAGS="$CFLAGS -I$dir/openssl"
+			sslincdir="$dir/openssl"
+			ssldir="$dir/.."
+		        break
+		fi
+	done
+
+	if test x_$found_ssl != x_yes; then
+        	{ { echo "$as_me:$LINENO: error: Cannot find ssl headers" >&5
+echo "$as_me: error: Cannot find ssl headers" >&2;}
+   { (exit 1); exit 1; }; }
+	else
+
+	        printf "SSL headers found in $ssldir\n";
+
+				echo "$as_me:$LINENO: checking for SSL libraries" >&5
+echo $ECHO_N "checking for SSL libraries... $ECHO_C" >&6
+		found_ssl=no
+		for dir in $ssl_lib_dir $ssl_dir /usr/lib64 /usr/lib /usr/local/lib /usr/lib/ssl /usr/ssl/lib /usr/openssl/lib /usr/pkg/lib  /usr/freeware/lib/openssl; do
+			ssllibdir="$dir"
+			if test -f "$dir/libssl.so"; then
+				found_ssl=yes
+			        break
+			fi
+		done
+
+		if test x_$found_ssl != x_yes; then
+        		{ { echo "$as_me:$LINENO: error: Cannot find ssl libraries" >&5
+echo "$as_me: error: Cannot find ssl libraries" >&2;}
+   { (exit 1); exit 1; }; }
+		else
+		        printf "SSL libraries found in $ssllibdir\n";
+
+			LDFLAGS="$LDFLAGS -L$ssllibdir";
+		        LIBS="$LIBS -lssl -lcrypto";
+
+			cat >>confdefs.h <<_ACEOF
+#define HAVE_SSL 1
+_ACEOF
+
+
+
+						echo ""
+			echo "*** Generating DH Parameters for SSL/TLS ***"
+			if test -f "$ssldir/sbin/openssl"; then
+				sslbin=$ssldir/sbin/openssl
+			else
+				sslbin=$ssldir/bin/openssl
+			fi
+			# awk to strip off meta data at bottom of dhparam output
+			$sslbin dhparam -C 512 | awk '/^-----/ {exit} {print}' > include/dh.h
+		fi
+	fi
+
+		echo "$as_me:$LINENO: checking for Kerberos include files" >&5
+echo $ECHO_N "checking for Kerberos include files... $ECHO_C" >&6
+	found_kerberos=no
+	for dir in $kerberos_inc_dir /usr/kerberos/include; do
+		kerbdir="$dir"
+		if test -f "$dir/krb5.h"; then
+			found_kerberos=yes
+			CFLAGS="$CFLAGS -I$kerbdir"
+			cat >>confdefs.h <<_ACEOF
+#define HAVE_KRB5_H 1
+_ACEOF
+
+						break
+		fi
+	done
+
+	if test x_$found_kerberos != x_yes; then
+		printf "could not find include files\n";
+	else
+		printf "found Kerberos include files in $kerbdir\n";
+	fi
+
+
+fi
+
 
                               ac_config_files="$ac_config_files Makefile src/Makefile subst"
 
@@ -6791,6 +6952,7 @@ s,@DBLIBS@,$DBLIBS,;t t
 s,@ndo2db_user@,$ndo2db_user,;t t
 s,@ndo2db_group@,$ndo2db_group,;t t
 s,@INSTALL_OPTS@,$INSTALL_OPTS,;t t
+s,@HAVE_SSL@,$HAVE_SSL,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
