AIX Init script changes

diff --git a/startup/bsd-init.in b/startup/bsd-init.in
--- a/startup/bsd-init.in
+++ b/startup/bsd-init.in
@@ -10,9 +10,19 @@ NDO2DB_CFG=@pkgsysconfdir@/ndo2db.cfg
 PID_DIR=@piddir@
 PID_FILE=@piddir@/ndo2db.pid
 
+# Get PID of running process
+ndo2db_get_pid() {
+	if [ -r "$PID_FILE" ]; then
+		pid=$(cat "$PID_FILE")
+	else
+		pid=$(ps -A -o pid,command|grep ndo2db|tr -s ' '|sed -e 's/^ //'|cut -d' ' -f1)
+	fi
+	echo $pid
+}
+
 # Start ndo2db
 ndo2db_start() {
-	echo -n "Starting ndo2db daemon: $NDO2DB_BIN - "
+	printf "Starting ndo2db daemon: $NDO2DB_BIN - "
 	if [ ! -d "$PID_DIR" ]; then
 		mkdir -p "$PID_DIR"
 	fi
@@ -26,16 +36,17 @@ ndo2db_start() {
 
 # Stop ndo2db
 ndo2db_stop() {
-	echo -n "Stopping ndo2db daemon - "
-	if [ -r "$PID_FILE" ]; then 
+	printf "Stopping ndo2db daemon - "
+	pid=`ndo2db_get_pid()`
+	if [ -n $pid ]; then
 		kill $(cat "$PID_FILE")
+		if [ $? = 0 ]; then
+			echo "stopped"
+		else
+			echo "failed"
+		fi
 	else
-		killall ndo2db
-	fi
-	if [ $? = 0 ]; then
-		echo "stopped"
-	else
-		echo "failed"
+		echo "Does not appear to be running"
 	fi
 }
 
@@ -48,12 +59,19 @@ ndo2db_restart() {
 
 # ndo2db status
 ndo2db_status() {
-	if test $BSDTYPE != aix; then
-		if ps -C ndo2db >/dev/null; then
-			echo "ndo2db is running."
+	pid=`ndo2db_get_pid()`
+	if [ -n $pid ]; then
+		if test $BSDTYPE = aix; then
+			if ps g -o pid
 		else
-			echo "ndo2db is stopped."
+			if ps -C ndo2db >/dev/null; then
+				echo "ndo2db is running."
+			else
+				echo "ndo2db is stopped."
+			fi
 		fi
+	else
+		echo "ndo2db is stopped."
 	fi
 }
 
@@ -71,11 +89,6 @@ case "$1" in
 	ndo2db_status
 	;;
 *)
-
-if test $BSDTYPE = aix; then
-	echo "Usage $0 start|stop|restart"
-else
 	echo "Usage $0 start|stop|restart|status"
-fi
 	;;
 esac
